### ISSUE TITLE
Repo needs a software license

### ISSUE THREAD

**Issue by jvasile** [LibertyDSNP/example-client#10]
This repo lacks a proper open source software license.  Creative Commons licenses aren't meant for code, and the CC folks suggest we use FOSS licenses: https://creativecommons.org/about/program-areas/software/

**Comment by kfogel** [comment]
@sbendar We've been going with Apache-2.0 elsewhere.  If that's the plan for this repository too, I'd be happy to prepare the PR (it'll only take a few minutes).

**Comment by kfogel** [comment]
Repository has a [license](https://github.com/LibertyDSNP/example-client/blob/main/LICENSE) now; closing this issue.
