### ISSUE TITLE
Wiki got lost

### ISSUE THREAD

**Issue by jvasile** [LibertyDSNP/example-client#11]
We have a github wiki for this client in the old repository.  Do we want to move it here?

**Comment by kfogel** [comment]
@sbendar, @claireolmstead, @wilwade: If you'd like the wiki content ported over, just enable the wiki in this repository and I can port over the full history from the old wiki.

(You might know this already, but just in case: GitHub wikis are just Git repositories themselves -- the name of the base repository with `.wiki` tacked on to the end.  So if you enable a wiki here, we can port the history over from the old Liberty30 wiki and push it into git@github.com:LibertyDSNP/example-client.wiki.git .)

**Comment by wilwade** [comment]
I don't think we want to port that? I'm not sure we want to use the github wiki system and instead the website documentation. Thoughts @claireolmstead?

**Comment by claireolmstead** [comment]
I was under the impression that the developer portal on the Project Liberty site would contain the docs for the Example Client, which I like becuase it ties the Example Client in with the rest of the product, rather than isolating it to the gihub repo/wiki. We can link the docs in the README.

**Comment by kfogel** [comment]
Amen to all that.
