### ISSUE TITLE
Torus login fails

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/example-client#131]
Issue description
---------------

Log in to example/sample client fails using Torus.

Reproduce Issue
---------------
1. Using Google Chrome (Version 94.0.4606.81 (Official Build) (64-bit)) on Windows 10 Home
2. In shell, start app using npm
3. Goto http://localhost:3000
4. Connect via Torus (set up account using Google)
5. Error

Expected result
---------------
- A detailed description of what you expected to happen

Actual result
---------------
- A detailed description of what actually happened

Additional details / screenshot
---------------
![image](https://user-images.githubusercontent.com/1135694/137223289-dd36e430-eb27-4bbd-9691-a93a96a64f8b.png)

**Comment by wilwade** [comment]
We started removing Torus in #135 and will complete it with #140.

Why remove Torus?

1. Keeping another wallet up to date was difficult
2. There wasn't much benefit from supporting it, although we retained to the abstraction so seeing how to integrate other wallets is still in the code
3. Local setup of Torus was adding unneeded complexity for the goal of being an example.
